### ISSUE TITLE
Support for ON CONFLICT

### ISSUE THREAD

**Issue by vitalif** [Suor/pg-bricks#11]
Hi!
Can you implement support for PostgreSQL 9.5+ extensions: ON CONFLICT DO UPDATE and ON CONFLICT DO NOTHING?
(see https://www.postgresql.org/docs/9.5/static/sql-insert.html)

**Comment by Suor** [comment]
Implemented in https://github.com/Suor/sql-bricks-postgres/commit/0e55ab2a4b804a1d73d9a5c7301585c149bfac6b
