### ISSUE TITLE
PG.connect is deprecated

### ISSUE THREAD

**Issue by gergely-ujvari** [Suor/pg-bricks#14]
PG 7.0 is out, and it makes PG.connect deprecated:
```
(STDERR) PG.connect is deprecated - please see the upgrade guide at https://node-postgres.com/guides/upgrading
```

According to the guide the fix should be trivial.

**Comment by gergely-ujvari** [comment]
Is this package is maintained? Do you accept PR?

**Comment by vitalif** [comment]
+1

**Comment by Suor** [comment]
Yes, I accept PRs.

**Comment by Suor** [comment]
Should be fixed with latest code, will release in a few days. Or once docs are ready)
