### ISSUE TITLE
Close all clients

### ISSUE THREAD

**Issue by ianlivingstone** [Suor/pg-bricks#3]
Right now its not possible to access the `pg` module (posgres driver) meaning it's not possible to end any of the created connections to the pg server.

This makes it very difficult to write integration tests.

**Comment by Suor** [comment]
So to close all clients in all pools you can:
```js
db.pg.end()
```
There is no simple way in node-postgres to close clients of particular pool, which `db.close()` supposed to do, so I leave this hanging for now. Corresponding node-postgres issue: https://github.com/brianc/node-postgres/issues/867
