### ISSUE TITLE
Native bindings support

### ISSUE THREAD

**Issue by danistefanovic** [Suor/pg-bricks#7]
Would be nice, if the user could decide whether to use [pg](https://github.com/brianc/node-postgres) or [pg-native](https://github.com/brianc/node-pg-native):
* native (C/C++) bindings for PostgreSQL increase the parsing speed by 20-30% 
* *pg-native* provides the same interface as *pg*

**Comment by Suor** [comment]
How do you propose making this to work? Always try `pg-native` first, then `pg`? Look for some env var? Change `.configure()` signature to accept some flag?

**Comment by danistefanovic** [comment]
I would try something like this: Use `pg-native` if available, or else fall back to `pg`.

```js
try {
    return require('pg').native;
} catch (e) {
    return require('pg');
}
```

What do you prefer?

**Comment by Suor** [comment]
Simple fallback doesn't work at this stage, see https://github.com/brianc/node-postgres/issues/940, will wait for Brians response.

**Comment by coagmano** [comment]
I've noticed `pg` and `pg-native` differ on a couple of things and aren't always kept in sync, so I'd prefer only using `pg-native` by explicit choice of the consumer

**Comment by Suor** [comment]
Supported through autouse now - https://github.com/Suor/pg-bricks/commit/9205beba5885ae93b54ac9a74395dc116750d8c0.

After some thought I think mirror API should be better:
```js
var pg = require('pg-bricks').configure(...);
pg.native.select().from('some_table').run();
// or
var pg = require('pg-bricks').native.configure(...);
```
